[package]
name = "rcx-timepin"
version = "0.1.0"
description = "Experimental no-value RCX Timepin public oracle evidence primitive"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]
name = "rcx_timepin"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = { version = "=1.0.2" }
pyth-solana-receiver-sdk = { version = "=2.0.0", features = ["pro-compatible"] }
solana-sha256-hasher = "=3.1.0"
