import { createDelegateActions } from './delegate-actions.mjs';
import { createGrantWallet } from './grant-wallet.mjs';
import { explorerLink } from './read-game.mjs';
import { formatChainTime } from './shot-view.mjs';
const $=id=>document.getElementById(id),web3=globalThis.solanaWeb3;
let config,connection,actions,controller,wallet=null,current=null,prepared=null,busy=false;
const query=new URLSearchParams(location.search),expectedOwner=query.get('player');
const json=x=>JSON.stringify(x,(_,v)=>typeof v==='bigint'?v.toString():v,2);
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function formIdentity(){if(!wallet?.publicKey)throw Error('Connect the wallet that owns the test credits');const player=wallet.publicKey.toBase58();if(expectedOwner&&expectedOwner!==player)throw Error('Connected wallet does not match the owner in this setup link');return{player,delegate:$('delegate').value.trim(),grantId:$('grant-id').value.trim()};}
function validAgent(){try{const delegate=new web3.PublicKey($('delegate').value.trim()).toBase58(),grantId=$('grant-id').value.trim(),player=expectedOwner||wallet?.publicKey?.toBase58();if(delegate==='11111111111111111111111111111111'||!/^[0-9a-f]{32}$/i.test(grantId)||/^0+$/.test(grantId))return false;if(player){if(!actions)return false;actions.deriveGrant({player,delegate,grantId});}return true;}catch{return false;}}
function presentForm(){const valid=validAgent();$('identity-summary').hidden=!valid;$('identity-summary').textContent=valid?'Agent '+$('delegate').value.trim():'';const ids=['max-shots','max-stake','max-gross','expiry-hours','min-interval'],values=ids.map(id=>$(id).value.trim());const complete=values.every(value=>/^[1-9][0-9]*$/.test(value));$('allowance-summary').textContent=complete?'Up to '+values[0]+' predictions · up to '+values[1]+' credits each':'Choose your allowance';$('allowance-detail').textContent=complete?values[2]+' credits total · '+values[3]+' hours · at least '+values[4]+' seconds apart':'Enter whole positive values. Exact limits are checked before review.';}
// Continue the existing private Bankr setup without a user API credential.
function bankrCheckRequest(){
 if(!config||!actions)throw Error('The devnet setup is still loading. Try again when it is available.');
 const address=expectedOwner||wallet?.publicKey?.toBase58();
 const delegate=$('delegate').value.trim(),grantId=$('grant-id').value.trim();
 const existingOnly=!query.has('player')&&!wallet?.publicKey&&!delegate&&!grantId;
 if(query.has('player')&&!expectedOwner)throw Error('The setup link has an invalid player address. Open a valid owner setup link.');
 if(!address&&!existingOnly)throw Error('Open the complete owner setup link, or clear both public agent fields to check only the existing Bankr setup.');
 let player=null;
 if(address){try{player=new web3.PublicKey(address).toBase58();}catch{throw Error('The setup link has an invalid player address. Open a valid owner setup link.');}
  if(player==='11111111111111111111111111111111')throw Error('Use a valid owner wallet address.');
  if(wallet?.publicKey&&wallet.publicKey.toBase58()!==player)throw Error('Connected wallet does not match the owner in this setup link.');
 }
 if((delegate||grantId)&&!validAgent())throw Error('Use both valid public agent details from the same setup link, or leave both fields empty to check the existing private setup.');
 const expected={clusterGenesis:config.clusterGenesis,economyHash:config.economyHash,rulesetHash:config.rulesetHash};
 if(player)expected.player=player;
 if(delegate){expected.delegate=delegate;expected.grantId=grantId.toLowerCase();}
 const identityNote=existingOnly?' No player, delegate or grant was supplied by this page. Read only the identity already associated with this original authenticated Bankr setup; do not choose, infer or create a replacement.':'';
 return 'Use the already installed ratchetx-g2 skill in this original authenticated private Bankr setup conversation. This is an existing-agent diagnostic, including SETUP_REQUIRED from an X status request.'+identityNote+' Expected public bindings, when present: '+JSON.stringify(expected)+'. Confirm this is the same Bankr account as the earlier setup and X request; an external Solana player address alone is not that confirmation. Retrieve the original installed absolute run.mjs path from the entry field of the earlier RUNTIME_INSTALLED tool result. Keep the same private RATCHET_G2_HOME; the installed launcher binds it to its own directory. Do not guess a new path or create a new identity. Check only whether that launcher and its adjacent identity.json exist and are readable, and return those booleans without paths or file contents. If the original path, account match or files are unavailable, report which is unavailable or unknown and stop. If accessible, using execute_cli, run that exact existing launcher with only the preflight argument once. Return its actual public JSON unchanged, including any refusal. Compare the returned player, delegate and grantId with the expected values when supplied. Genesis, Economy and Ruleset are expected configuration pins validated internally by the runtime; do not invent fields omitted from its output. Never repeat expected values as if they were observed. If the observed identity differs, report that and stop. Do not reinstall, initialize, run status, request an API key, change environment variables, schedule anything, grant, fund, sign, send a transaction, play or post on X. Never execute a bare g2-session.mjs companion or copy private state. Keep all private keys and reveal state inside the existing runtime; do not read or print private files, credentials or environment values. State separately whether this host can persist signed records before sending and reliably resume finish within the reveal window; if unknown, say unknown. A successful public read alone does not prove those host guarantees. Stop after this check.';
}
function bankrCheckControls(){try{bankrCheckRequest();$('copy-bankr-check').disabled=busy;if(!$('bankr-check-request').textContent&&$('copy-bankr-check').textContent==='1. Copy agent check')$('bankr-check-hint').textContent='Prepares a check of your existing setup. It does not approve a permission or start a game.';}catch(e){$('copy-bankr-check').disabled=true;$('bankr-check-hint').textContent=e.message;}}
function resetBankrCheck(){$('copy-bankr-check').textContent='1. Copy agent check';$('bankr-check-request').textContent='';$('bankr-check-request').hidden=true;bankrCheckControls();}
function controls(){bankrCheckControls();for(const id of ['connect','refresh'])$(id).disabled=busy||(!wallet&&id!=='connect');$('review').disabled=busy||!config||!validAgent();$('review').firstChild.textContent=wallet?'Review permission ':'Connect & review ';$('approve').disabled=busy||!prepared;$('revoke').disabled=busy||!controller||!wallet?.publicKey||wallet.publicKey.toBase58()!==current?.player?.toBase58()||!current?.grant||current.grant.revoked===1||current.pending;$('copy-session').disabled=!current||busy;for(const input of document.querySelectorAll('input'))input.disabled=busy;}
async function run(work){if(busy)return;busy=true;controls();try{await work();}catch(e){invalidate();status(e.message||String(e),true);}finally{busy=false;controls();}}
function invalidate(){prepared=null;$('review-panel').hidden=true;controls();}
function fact(root,label,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;root.append(dt,dd);}
function render(value){current=value;const grant=value.grant,usage=value.usage;$('grant-facts').replaceChildren();
 const state=value.pending?'Transaction unresolved':!grant?'No permission yet':usage.revoked?'Revoked':usage.expired?'Expired':usage.minimumStakePermission.ok?'Permission active':'Limit reached / waiting';
 $('grant-state').textContent=state;$('grant-state').dataset.active=String(!!grant&&usage.minimumStakePermission.ok&&!value.pending);$('grant-state').dataset.revoked=String(!!usage?.revoked);
 fact($('grant-facts'),'Owner',value.player.toBase58());fact($('grant-facts'),'Agent',value.delegate.toBase58());
 if(grant){fact($('grant-facts'),'Predictions left',usage.shotsRemaining+' / '+grant.maxShots);fact($('grant-facts'),'Gross credits left',String(usage.grossStakeRemaining));fact($('grant-facts'),'Per prediction',String(grant.maxStake));fact($('grant-facts'),'Minimum gap',grant.minIntervalSeconds+' sec');fact($('grant-facts'),'Expires',formatChainTime(grant.expiresAtTs));}
 $('credit-note').textContent=value.ledger?'Owner ledger: '+value.ledger.credits+' test credits · '+value.ledger.xp+' XP. Permissions do not add credits.':'This owner has no G2 test-credit ledger. A grant can be registered, but no prediction can spend credits it does not have.';
 $('chain-links').replaceChildren();const link=(label,kind,address)=>{const a=document.createElement('a');a.textContent=label+' ↗';a.href=explorerLink({genesisHash:config.clusterGenesis,kind,value:String(address)});a.target='_blank';a.rel='noopener noreferrer';$('chain-links').append(a);};link('Inspect permission','address',value.address);
 if(value.transactionRecord?.signature)link('Inspect last transaction','tx',value.transactionRecord.signature);
 const session={schema:1,clusterGenesis:config.clusterGenesis,economyHash:config.economyHash,rulesetHash:config.rulesetHash,player:value.player.toBase58(),delegate:value.delegate.toBase58(),grantId:Array.from(value.grantId,b=>b.toString(16).padStart(2,'0')).join('')};$('session-details').textContent=json(session);
 controls();
}
async function refresh(){invalidate();const value=await controller.reconcile(formIdentity());render(value);status(value.pending?'A transaction is unresolved. Its signature is saved; refresh to check before another approval.':'Permission and credit ledger read from Solana devnet.');}
function review(plan){prepared=plan;render(plan.context);$('review-panel').hidden=false;$('review-facts').replaceChildren();const revoke=plan.action==='revoke_delegate',limits=plan.intent.limits;$('review-title').textContent=revoke?'Stop new predictions':'Your exact permission';
 $('review-summary').textContent=revoke?'This permanently revokes this grant. Existing sealed predictions remain finishable by their original agent.':'At most '+limits.maxShots+' predictions, '+limits.maxStake+' test credits each and '+limits.maxGrossStake+' gross credits total. Minimum gap '+limits.minIntervalSeconds+' seconds.';
 fact($('review-facts'),'Network','Solana devnet');fact($('review-facts'),'Owner',plan.player.toBase58());fact($('review-facts'),'Agent',plan.delegate.toBase58());if(limits)fact($('review-facts'),'Expires',formatChainTime(limits.expiresAtTs));fact($('review-facts'),'Network fee',plan.networkFee.lamports===null?'Unavailable (rent is extra)':plan.networkFee.lamports+' lamports + account rent');
 $('instruction').textContent=json({operation:plan.action,instructions:plan.instructionDetails,blockhash:plan.blockhash,lastValidBlockHeight:plan.lastValidBlockHeight,simulation:plan.simulation.passed});$('approve').firstChild.textContent=revoke?'Revoke in wallet ':'Approve in wallet ';status('The exact unsigned permission passed simulation. Review the limits and wallet transaction before approving.');controls();$('review-title').focus();
}
async function connectWallet(){const candidate=globalThis.phantom?.solana||globalThis.solflare||globalThis.solana;if(!candidate?.connect||!candidate?.signTransaction)throw Error('Open this page in your Solana wallet browser or enable its extension to approve the on-chain permission');await candidate.connect();if(!candidate.publicKey)throw Error('No wallet connected');wallet=candidate;controller=createGrantWallet({web3,connection,config,wallet,onStatus:e=>status(e.phase==='signing'?'Review the permission in your wallet.':e.phase==='sending'?'Sending the owner-signed permission to devnet.':e.phase==='confirming'?'Waiting for devnet confirmation.':'Reading the permission state.')});$('connect').textContent=wallet.publicKey.toBase58().slice(0,6)+'…'+wallet.publicKey.toBase58().slice(-5);resetBankrCheck();candidate.on?.('accountChanged',()=>{resetBankrCheck();current=null;prepared=null;$('review-panel').hidden=true;status('Wallet changed. Refresh the permission for the selected owner.');controls();});}
$('connect').onclick=()=>run(async()=>{if(wallet){await wallet.disconnect?.();wallet=null;controller=null;current=null;resetBankrCheck();invalidate();$('connect').textContent='Connect owner wallet';$('grant-state').textContent='Not read yet';return;}await connectWallet();if(validAgent())await refresh();else status('Wallet connected. Open your agent setup link or enter its public details.');});
$('refresh').onclick=()=>run(refresh);
$('review').onclick=()=>run(async()=>{invalidate();if(!wallet)await connectWallet();const id=formIdentity();const read=await controller.reconcile(id);render(read);if(read.pending)throw Error('An earlier transaction is unresolved. Refresh it first');const hours=Number($('expiry-hours').value);if(!Number.isInteger(hours)||hours<1||hours>720)throw Error('Choose an expiry from 1 to 720 hours');const plan=await controller.prepareGrant({...id,maxStake:$('max-stake').value,maxGrossStake:$('max-gross').value,maxShots:$('max-shots').value,minIntervalSeconds:$('min-interval').value,expiresAtTs:read.chainNowTs+BigInt(hours*3600),expectedGrantHash:read.grantHash??undefined});review(plan);});
$('revoke').onclick=()=>run(async()=>{invalidate();const plan=await controller.prepareRevoke({...formIdentity(),expectedGrantHash:current.grantHash});review(plan);});
$('approve').onclick=()=>run(async()=>{const plan=prepared;prepared=null;const result=await controller.approve(plan);$('review-panel').hidden=true;render(result);status(result.grant.revoked===1?'Permission revoked on chain. New predictions are blocked.':'Permission confirmed on chain. Your agent can now read it; you do not need to copy these details again. Its runtime must still be ready before playing.');});
$('copy-session').onclick=async()=>{try{await navigator.clipboard.writeText($('session-details').textContent);$('copy-session').textContent='Public session copied';}catch{const range=document.createRange();range.selectNodeContents($('session-details'));const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);status('Copy is unavailable. The public session text is selected below.');}};
$('copy-bankr-check').onclick=async()=>{let text;try{text=bankrCheckRequest();}catch(e){resetBankrCheck();status(e.message,true);return;}try{await navigator.clipboard.writeText(text);$('copy-bankr-check').textContent='Check copied';$('bankr-check-request').textContent='';$('bankr-check-request').hidden=true;$('bankr-check-hint').textContent='Copied. Open Bankr and paste into your existing private chat.';}catch{$('bankr-check-request').textContent=text;$('bankr-check-request').hidden=false;$('bankr-check-hint').textContent='Copy is unavailable. Select the request below and paste it into your existing private Bankr chat.';$('bankr-check-request').focus();}};
$('copy-install').onclick=async()=>{let player;try{const address=expectedOwner||wallet?.publicKey?.toBase58();player=address?new web3.PublicKey(address).toBase58():null;}catch{status('The setup link has an invalid player address. Open a valid owner setup link.',true);return;}const owner=player?'for public Solana player wallet '+player:'for the public Solana player wallet I select';const text='Install the RatchetX G2 skill at https://github.com/3esign/ratchetx/tree/40cb6700128a657f09e978764315fe6c6e8a4b1e/skills/ratchetx-g2 . Keep the previous RatchetX skill intact. In this authenticated private session, install and initialize the G2 runtime '+owner+'. Use one private persistent RATCHET_G2_HOME. In two separate execute_cli invocations, run init for that same player and confirm the delegate address and grant ID are identical. Return only the public setup link, both public identity results, and whether this host can persist signed records before sending and reliably resume finish within the reveal window. If those host guarantees are unknown, say so and stop before granting or playing. Keep all private keys and reveal state inside this runtime. Do not send a transaction or play yet.';try{await navigator.clipboard.writeText(text);$('copy-install').textContent=player?'Wallet setup request copied':'Setup request copied';}catch{$('install-request').textContent=text;$('install-request').hidden=false;status('Copy is unavailable. The setup request is selectable below.');}};
for(const input of document.querySelectorAll('input'))input.addEventListener('input',()=>{resetBankrCheck();current=null;presentForm();invalidate();$('grant-state').textContent='Details changed — refresh';$('grant-state').dataset.active='false';});
try{if(!web3)throw Error('The local Solana client did not load');const response=await fetch('/lib/g2/devnet-config.json',{cache:'no-store'});if(!response.ok)throw Error('Devnet configuration unavailable');config=await response.json();connection=new web3.Connection('https://api.devnet.solana.com',{commitment:'confirmed',disableRetryOnRateLimit:true});actions=createDelegateActions({web3,connection,config});if(query.has('delegate'))$('delegate').value=query.get('delegate');if(query.has('grant'))$('grant-id').value=query.get('grant');presentForm();if(!query.has('player')&&!$('delegate').value.trim()&&!$('grant-id').value.trim())status('Already installed? Continue in Bankr to locate the existing setup. No wallet connection is needed for that check.');if(validAgent()){$('identity-fields').open=false;$('runtime-setup').open=false;}if(expectedOwner&&query.get('delegate')&&query.get('grant')){const value=await actions.readGrant({player:expectedOwner,delegate:query.get('delegate'),grantId:query.get('grant')});render(value);status('Public permission state read from devnet. Connect its owner wallet to create, change or revoke it.');}}catch(e){status(e.message||String(e),true);}controls();
